const ADD_CONTACT = "ADD_CONTACT";
const EDIT_CONTACT = "EDIT_CONTACT";
const REMOVE_CONTACT = "REMOVE_CONTACT";
const FETCH_CONTACTS = "FETCH_CONTACTS";
const POPULATE_CONTACTS = "POPULATE_CONTACTS";

export {
    ADD_CONTACT,
    EDIT_CONTACT,
    REMOVE_CONTACT,
    FETCH_CONTACTS,
    POPULATE_CONTACTS
};